services:
  mysql:
    image: mysql:8
    container_name: santa_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Abcd123@
      MYSQL_DATABASE: santa_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - santa_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: santa_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: tjsdnd11227
    networks:
      - santa_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: santa_app
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/santa_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Abcd123@
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: tjsdnd11227
    networks:
      - santa_net

volumes:
  mysql_data:

networks:
  santa_net:
